### ISSUE TITLE
Compiled Failed

### ISSUE THREAD

**Issue by jchang98** [thu-coai/DA-Transformer#1]
- python 3.7.12
- pytorch 1.11.0+cu102
- gcc 5.4

I have modified the cloneable.h file according to the FAQs section, but I still encounter the following error when the program is running. Please tell me how can i fix it?

<pre> 
Traceback (most recent call last):  
File /home/env/nat/lib/python3.7/site-packages/torch/utils/cpp_extension.py, line 1746, in _run_ninja_build   env=env)
File /home/env/nat/lib/python3.7/subprocess.py, line 512, in run   output=stdout, stderr=stderr)  subprocess.CalledProcessError: Command [ninja, -v] returned non-zero exit status 1.
The above exception was the direct cause of the following exception:

RuntimeError: Error building extension 'dag_loss_fn': [1/2] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=dag_loss_fn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/env/nat/lib/python3.7/site-packages/torch/include -isystem /home/env/nat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/env/nat/lib/python3.7/site-packages/torch/include/TH -isystem /home/env/nat/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/env/nat/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -DOF_SOFTMAX_USE_FAST_MATH -std=c++14 -c /home/DA-Transformer/fs_plugins/custom_ops/logsoftmax_gather.cu -o logsoftmax_gather.cuda.o 
FAILED: logsoftmax_gather.cuda.o 

/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=dag_loss_fn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/env/nat/lib/python3.7/site-packages/torch/include -isystem /home/env/nat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/env/nat/lib/python3.7/site-packages/torch/include/TH -isystem /home/env/nat/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/env/nat/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -DOF_SOFTMAX_USE_FAST_MATH -std=c++14 -c /home/DA-Transformer/fs_plugins/custom_ops/logsoftmax_gather.cu -o logsoftmax_gather.cuda.o 
/home/DA-Transformer/fs_plugins/custom_ops/logsoftmax_gather.cu:31:23: fatal error: cub/cub.cuh: No such file or directory compilation terminated.
ninja: build stopped: subcommand failed
</pre>

**Comment by hzhwcmhf** [comment]
It seems that PyTorch1.11 removes cub from the default including directory. **A direct workaround is using Pytorch1.10.**

I am trying to include ``cub`` in pytorch1.11 and will update this issue if I find an solution.

**Comment by jchang98** [comment]
> It seems that PyTorch1.11 removes cub from the default including directory. **A direct workaround is using Pytorch1.10.**
> 
> I am trying to include `cub` in pytorch1.11 and will update this issue if I find an solution.

I try to reinstall pytorch1.10.1, but it doesn't work (T⌓T)

**Comment by hzhwcmhf** [comment]
I am trying to reproduce your environment... it may take some times before I can find a solution.

If possible, you can also try using cuda>=11.0.
Or just skip cuda compiling by adding the following arguments:

```
--torch-dag-loss                  # Use torch implementation for dag loss instead cuda implementation. It may become slower and consume more memory.
--torch-dag-best-alignment        # Use torch implementation for best-alignment instead cuda implementation. It may become slower and consume more memory.
--torch-dag-logsoftmax-gather     # Use torch implementation for logsoftmax-gather instead cuda implementation. It may become slower and consume more memory.
```

**Comment by jchang98** [comment]
> I am trying to reproduce your environment... it may take some times before I can find a solution.
> 
> If possible, you can also try using cuda>=11.0. Or just skip cuda compiling by adding the following arguments:
> 
> ```
> --torch-dag-loss                  # Use torch implementation for dag loss instead cuda implementation. It may become slower and consume more memory.
> --torch-dag-best-alignment        # Use torch implementation for best-alignment instead cuda implementation. It may become slower and consume more memory.
> --torch-dag-logsoftmax-gather     # Use torch implementation for logsoftmax-gather instead cuda implementation. It may become slower and consume more memory.
> ```

Okay, thanks!

**Comment by hzhwcmhf** [comment]
@jchang98  I have pushed an update which manuanlly includes the cub library. Please re-clone this repo and try again.

**Comment by sudanl** [comment]
> I am trying to reproduce your environment... it may take some times before I can find a solution.
> 
> If possible, you can also try using cuda>=11.0. Or just skip cuda compiling by adding the following arguments:
> 
> ```
> --torch-dag-loss                  # Use torch implementation for dag loss instead cuda implementation. It may become slower and consume more memory.
> --torch-dag-best-alignment        # Use torch implementation for best-alignment instead cuda implementation. It may become slower and consume more memory.
> --torch-dag-logsoftmax-gather     # Use torch implementation for logsoftmax-gather instead cuda implementation. It may become slower and consume more memory.
> ```

- python 3.7.0
- gcc 4.8.5
- torch 1.10.1+cuda 11.3

Hello! I have also modified the cloneable.h file according to the FAQs section but encountered the following error. Do you have any advice for me?



```
Traceback (most recent call last):
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/data/home/USERNAME/DA-Transformer/fairseq_cli/train.py", line 530, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/data/home/USERNAME/DA-Transformer/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/home/USERNAME/DA-Transformer/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/data/home/USERNAME/DA-Transformer/fairseq_cli/train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data/home/USERNAME/DA-Transformer/fairseq_cli/train.py", line 305, in train
    log_output = trainer.train_step(samples)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data/home/USERNAME/DA-Transformer/fairseq/trainer.py", line 830, in train_step
    **extra_kwargs,
  File "/data/home/USERNAME/DA-Transformer/fs_plugins/tasks/translation_lev_modified.py", line 195, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/USERNAME/DA-Transformer/fs_plugins/criterions/nat_dag_loss.py", line 266, in forward
    outputs = model(src_tokens, src_lengths, prev_output_tokens, tgt_tokens, glat, glat_function)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/USERNAME/DA-Transformer/fairseq/distributed/module_proxy_wrapper.py", line 56, in forward
    return self.module(*args, **kwargs)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/USERNAME/DA-Transformer/fs_plugins/models/glat_decomposed_with_link.py", line 250, in forward
    prev_output_tokens, tgt_tokens, glat_info = glat_function(self, word_ins_out, tgt_tokens, prev_output_tokens, glat, links=links)
  File "/data/home/USERNAME/DA-Transformer/fs_plugins/criterions/nat_dag_loss.py", line 213, in glat_function
    word_ins_out, match = dag_logsoftmax_gather_inplace(word_ins_out, tgt_tokens.unsqueeze(1).expand(-1, prelen, -1))
  File "/data/home/USERNAME/DA-Transformer/fs_plugins/custom_ops/dag_loss.py", line 206, in forward
    selected_result = get_dag_kernel().logsoftmax_gather(word_ins_out, select_idx, require_gradient)
  File "/data/home/USERNAME/DA-Transformer/fs_plugins/custom_ops/dag_loss.py", line 60, in get_dag_kernel
    extra_include_paths=extra_include_paths,
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/data/home/USERNAME/anaconda3/envs/DA-Trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /data/home/USERNAME/.cache/torch_extensions/py37_cu113/dag_loss_fn/dag_loss_fn.so: cannot open shared object file: No such file or directory
```

**Comment by hzhwcmhf** [comment]
@sudanl Can you run the script with only one GPU (single process)? 
It only says that the Cuda program is not correctly compiled but not shows the real errors.
